### ISSUE TITLE
Add support for LZ4 compression

### ISSUE THREAD

**Issue by bnham** [mongodb-partners/mongo-rocks#10]
It'd be nice to add support for LZ4 decompression for CPU-bound workloads since LZ4 seems to use less CPU than Snappy.

**Comment by igorcanadi** [comment]
Thanks to @igorsol , the support for LZ4 is now available in master: https://github.com/mongodb-partners/mongo-rocks/commit/7933946818c23bd49488b906afe69b427291a497
