### ISSUE TITLE
Failed: compile_all on Ubuntu 14.04 (RocksDB) [MongoDB (master) @ 33990519] // RocksSnapshotManager::createSnapshot is marked 'final' but is not a virtual function

### ISSUE THREAD

**Issue by IanWhalen** [mongodb-partners/mongo-rocks#109]
I believe this is new and superseding the prior reported failure?

https://jira.mongodb.org/browse/SERVER-31463

**Comment by igorcanadi** [comment]
Yup, this is caused by https://github.com/mongodb/mongo/commit/7ef892d32c0507c57eda86ffc591ba5555eb78c6, looks like the fix would be to just remove that function, like what happened in WiredTiger.

**Comment by igorcanadi** [comment]
https://github.com/mongodb-partners/mongo-rocks/commit/01c6bb3367c981a0d6bc20f3f4e7c95eb41a7e41
