### ISSUE TITLE
Some code that is not used

### ISSUE THREAD

**Issue by wolfkdy** [mongodb-partners/mongo-rocks#114]
I'm reviewing code from my team-members these days, which is about mongoRocks and found unused code here, which proves to be from the open-source version.
https://github.com/mongodb-partners/mongo-rocks/blob/d1ac58583c777a2903ba3d0339ceb53f5b55917f/src/rocks_recovery_unit.cpp#L441

**Comment by igorcanadi** [comment]
Good point, thanks. Fixed here: https://github.com/mongodb-partners/mongo-rocks/commit/3f27e4930cc688fc403a63df099830e2d47dc120
