### ISSUE TITLE
Is there one rocksdb database / database?

### ISSUE THREAD

**Issue by benoitc** [mongodb-partners/mongo-rocks#14]
Is a rocksdb storage using  1 or more database/rocksdb instance per dbs?

**Comment by igorcanadi** [comment]
It's using 1 rocksdb database per mongodb instance.

**Comment by benoitc** [comment]
@igorcanadi so mongodb [databases](https://docs.mongodb.org/manual/reference/glossary/#term-database) share the same instance of a rocksdb? How it's organised? Do you maintain one column / db or smth? I'm curious about your design :)

**Comment by igorcanadi** [comment]
Yup, mongo databases share the same instance of RocksDB. For each collection and index, there's a 4-byte prefix. All keys in that collection/index are stored with that prefix. We actually don't treat database as a separate concept on the storage engine layer -- it's just a prefix of a collection. So if you have database `a`, collection `b`, we'd just store it as `a.b`

**Comment by benoitc** [comment]
@igorcanadi thanks for the answer (sorry for the delay to answer). I'm curious about the reasoning of it since it means they are sharing the same wall it makes somehow most of the writes serialised. is there any rationnal wrote somewhere?

**Comment by igorcanadi** [comment]
Correct, sharing a single WAL makes writes serialized. However, we implemented the concurrent memtable inserts, so writes should not be a bottleneck anymore: http://smalldatum.blogspot.com/2016/02/concurrent-inserts-and-rocksdb-memtable.html

If you want to make writes even faster, you can create multiple mongod processes in a single host. That's what we do internally with mysql.

**Comment by benoitc** [comment]
thanks for the answer, closing the issue now :)
