### ISSUE TITLE
Issues during compile

### ISSUE THREAD

**Issue by dinesh-chander** [mongodb-partners/mongo-rocks#140]
I'm trying to compile percona-server-mongodb version 3.6.1-1.0 with rocksdb support. I got this error 

```
Skipping ranlib for libtool generated target build/opt/mongo/util/libntservice.a
In file included from src/mongo/db/storage/rocks/src/rocks_server_status.cpp:46:
In file included from src/mongo/db/storage/rocks/src/rocks_recovery_unit.h:48:
src/mongo/db/storage/rocks/src/rocks_compaction_scheduler.h:46:5: error: class 'WriteOptions' was previously declared as a struct [-Werror,-Wmismatched-tags]
    class WriteOptions;
    ^
/usr/local/include/rocksdb/options.h:1097:8: note: previous use is here
struct WriteOptions {
       ^
src/mongo/db/storage/rocks/src/rocks_compaction_scheduler.h:46:5: note: did you mean struct here?
    class WriteOptions;
    ^~~~~
    struct
Compiling build/opt/mongo/db/ftdc/ftdc_server.o
Generating library build/opt/mongo/db/libmongohasher.a
Skipping ranlib for libtool generated target build/opt/mongo/db/libmongohasher.a
```
I'm using this command for compilation

```scons -j 8 --allocator=auto --release=RELEASE --build-dir="~/projects/percona-server-mongodb-3.6.1-1.0/build" --rocksdb=on --ssl=SSL --wiredtiger=off --mmapv1=off --inmemory=off --hotbackup=HOTBACKUP --dbg=off --opt=on CPPPATH=/usr/local/opt/openssl/include LIBPATH=/usr/local/opt/openssl/lib```

I have installed the rocksdb using homebrew. Am I doing something wrong?

Btw I'm trying this on macosx high sierra.

**Comment by igorcanadi** [comment]
Hey @dinesh-chander, thanks for the report, I just committed https://github.com/mongodb-partners/mongo-rocks/commit/c6576fb80c1fc348ef9a791d4b6cc9ce87ea80a9, does that fix your problem? Feel free to reopen the issue if it doesn't.
