### ISSUE TITLE
Support for MongoDB 4.0 

### ISSUE THREAD

**Issue by zydcom** [mongodb-partners/mongo-rocks#145]
MongoDB 4.0.0 is released last month，it will support multi-documents transaction which is a great feature for MongoDB users. We have some MongoDB instances armed with mongorocks，would you like to support MongoDB 4.0 ？

**Comment by baiwfg2** [comment]
Any plan on this ?

**Comment by igorcanadi** [comment]
Hi @baiwfg2 and @zydcom, thank you for your interest. Unfortunately, MongoRocks is no longer being actively maintained. MongoDB has made great strides in recent versions with multi-document transactions, which rely on extensive transaction support on the storage engine layer. As such, implementing a MongoDB storage engine API became more complicated and is not a project me or anybody involved in the project has time to embark on. I am happy to help with the project if anybody decides to pursue this, though.

**Comment by wolfkdy** [comment]
@igorcanadi  the t/o txn manager is possible in rocksdb with riversand's user-timestamp proj.
I proposaled a t/o txn mgr layer over rocksb https://github.com/facebook/rocksdb/issues/6281
it's in fact a proposal for rocksdb's support for mongo4+. Just now, I released a potential impl, which needs more work to be compatible with rocksdb's branch, because we developed it in a private branch, which is already diverged with the official one. The impl can be found here https://github.com/facebook/rocksdb/pull/6407, from the apis' view, you may find they are designed  
for mongo.

**Comment by igorcanadi** [comment]
Thank you @wolfkdy for the response, I was wondering what was happening with your planned support for MongoRocks 4.0. Is this still an active project on your side?

**Comment by wolfkdy** [comment]
@igorcanadi 
```
I was wondering what was happening with your planned support for MongoRocks 4.0
```
+ We successed to support Mongo4.0 over mongoRocks. To fulfill this, we made great effort to
understand wiredTiger's timestamp project and did almost the same work over Rocksdb. which can be found here https://github.com/wolfkdy/rocksdb/commits/timestamp_ordering_txn
+ However, we are not following official Mongodb's shard-nothing architecture. So I think the MongoRocks has been far diverged with the original one and maybe not meaningful for the community. So we dont have the plan to release this part.
```
Is this still an active project on your side
```
+ MongoRocks 4.0 is an active project on my side. To obey sspl, we develop it under Mongo4.0.3. As I've said, it has diverged, binded tightly with our own new architecture.
+ the [timestamp_ordering_txn](https://github.com/wolfkdy/rocksdb/commits/timestamp_ordering_txn)  is compilable, runnable and have demos to show how to use. It has the matchable apis as wiredTiger 3.0, which is used by mongodb4.0.3. The transaction part is fulfilled, So life will be easier If someone has the ambitious to contribute to community's MongoRocks4.0.
+ Maybe I have the ambitious to continue community's mongoRocks, but i'm not sure I have enough time. If someone has, let me know, I will also provide help

**Comment by wolfkdy** [comment]
After some thoughts, I decide to make a pr to mongoRocks4.0.3, I think the early work can be published in less than one and a half months, as I once promised to @igorcanadi . I'll try to fulfill this with my little personal time. The development progress can be found [here](https://github.com/wolfkdy/mongo-rocks/tree/v4.0)

**Comment by igorcanadi** [comment]
This is excellent news, thank you @wolfkdy ! I hope @siying can help with merging the relevant parts from transactional manager into upstream RocksDB.

**Comment by wolfkdy** [comment]
@igorcanadi  mr is ready https://github.com/mongodb-partners/mongo-rocks/pull/149

**Comment by wolfkdy** [comment]
done and close
