### ISSUE TITLE
Google Group is down

### ISSUE THREAD

**Issue by jorisw** [mongodb-partners/mongo-rocks#161]
The README refers to a Google Group that no longer seems to be there.

<img width="475" alt="image" src="https://user-images.githubusercontent.com/30017/104009868-f4029700-51ab-11eb-8b33-4ceae4585f75.png">

The question I was going to post was, what's the general status of this project? Should I pursue using it if I'm looking for high performance for large mongo databases (70+ GB) ?

Also, where are the Mac build instructions?

**Comment by wolfkdy** [comment]
@jorisw 
1) the google group is alive there. but it is set only visible to developers now, I'll update the readme
2) this project aims to use rocksdb as the underneath storage engine of mongodb(like mongodb's mmapv1, wiredTiger engine)
3) currently mongoRocks3.4 and 4.0 are the two stable branches.
4) I believe this project is for people who have interests about rocksdb and mongodb's source code, and people who develop database kernels.
5) 70GB is not a large working set. the official mongodb works well for your working set. And mongoRocks can also work well for that.
6) I've successed to build mongodb with mongoRocks with the guide of [README](https://github.com/mongodb-partners/mongo-rocks), there is no big difference.
7) Tell me why you need to build your own mongodb binary? why not using a community mongodb rpm?

**Comment by jorisw** [comment]
Thanks @wolfkdy . I was actually just curious about MongoDB optimization for high performance and stumbled upon RocksDB as part of my research.
