### ISSUE TITLE
SIGILL after compiling rocksdb with PORTABLE=1

### ISSUE THREAD

**Issue by mutex007** [mongodb-partners/mongo-rocks#21]
Hi, 

The binaries do work on the target machine on which they were built, however if i try the binaries on a different machine same os and setup but with different processors, it does not work.

Could you please advice on this. 

mongod(_ZN5mongo15printStackTraceERSo+0x32) [0x103d272]
 mongod(+0xC3CB23) [0x103cb23]
 mongod(+0xC3CE84) [0x103ce84]
 libpthread.so.0(+0x10340) [0x7fd4afd02340]
 mongod(_ZN7rocksdb18OldInfoLogFileNameERKSsmS1_S1_+0x9B) [0x155151b]
 mongod(_ZN7rocksdb23CreateLoggerFromOptionsERKSsRKNS_9DBOptionsEPSt10shared_ptrINS_6LoggerEE+0x537) [0x15fc127]
 mongod(_ZN7rocksdb15SanitizeOptionsERKSsRKNS_9DBOptionsE+0x777) [0x1515497]
 mongod(_ZN7rocksdb6DBImplC1ERKNS_9DBOptionsERKSs+0x5D) [0x152939d]
 mongod(_ZN7rocksdb2DB4OpenERKNS_9DBOptionsERKSsRKSt6vectorINS_22ColumnFamilyDescriptorESaIS7_EEPS6_IPNS_18ColumnFamilyHandleESaISD_EEPPS0_+0xA3F) [0x152ebcf]
 mongod(_ZN7rocksdb2DB4OpenERKNS_7OptionsERKSsPPS0_+0x156) [0x152fff6]
 mongod(_ZN5mongo11RocksEngineC2ERKSsb+0x3E4) [0xe1b0f4]
 mongod(+0xA26A54) [0xe26a54]
 mongod(_ZN5mongo23GlobalEnvironmentMongoD22setGlobalStorageEngineERKSs+0x32A) [0xb2b1aa]
 mongod(_ZN5mongo13initAndListenEi+0x421) [0x8aebc1]
 mongod(main+0x159) [0x82b659]

It appears the invalid instruction happens in this function

std::string OldInfoLogFileName(const std::string& dbname, uint64_t ts,
    const std::string& db_path, const std::string& log_dir) {
  char buf[50];
  snprintf(buf, sizeof(buf), "%llu", static_cast<unsigned long long>(ts));

  if (log_dir.empty()) {
    return dbname + "/LOG.old." + buf;
  }

  InfoLogPrefix info_log_prefix(true, db_path);
  return log_dir + "/" + info_log_prefix.buf + ".old." + buf;
}

**Comment by igorcanadi** [comment]
Hey @mutex007, any reason why you closed this task? It would be good to debug it if it's still an issue.

**Comment by mutex007** [comment]
@igorcanadi, Issue resolved, forgot to reinstall the binaries back in usr/lib as i initially compiled without the portable. Cleared it and recompiled mongod. All is working very well now. 
Regards

**Comment by igorcanadi** [comment]
Nice! Would be good to learn about your use-case for MongoRocks and any performance data you get from it.

**Comment by mutex007** [comment]
Sure will share a link to a blog post on this thread sometime in the near future. Our use case mainly is to run tons of small dedicated databases (dedicated mongod), which can easily bounce from machine to machine and also to be able to constrain the memory usage of the storage layer. we were considering LVM snapshot with oplog tailing. After we move the snapshot to the new machine and then sync it, but of course MMAPv1 has too many cons especially in regards to memory usage and write performance and startup time. Wired tiger we could not even consider, it makes a mess with too many files on disk. With rocksdb we can quickly snapshot, and then tail the oplog to keep the database in sync as we scale the clients database. The boot time is perfect and the on disk file sizes are splendid no more  having to pre-allocate huge files and fill them with zeros. Will share our complete use case when in finish the blog post.

**Comment by igorcanadi** [comment]
Sounds great @mutex007, looking forward to the blog post!
