### ISSUE TITLE
Build errors on Mac

### ISSUE THREAD

**Issue by mark-lb** [mongodb-partners/mongo-rocks#28]
Following the standard build instructions, XCode 7.3.1
Similar errors on master as well as 3.2 branch and r3.2.7 tag, when paired with similar branch/tag on mongo

`src/mongo/db/modules/rocks/src/rocks_recovery_unit.cpp:65:31: error: moving a temporary object prevents copy elision [-Werror,-Wpessimizing-move]
                  _nextPrefix(std::move(rocksGetNextPrefix(_prefix))),
                              ^
src/mongo/db/modules/rocks/src/rocks_recovery_unit.cpp:65:31: note: remove std::move call here
                  _nextPrefix(std::move(rocksGetNextPrefix(_prefix))),
                              ^~~~~~~~~~                           ~
Compiling build/opt/mongo/db/modules/rocks/src/rocks_transaction.o
src/mongo/db/modules/rocks/src/rocks_record_store.cpp:206:59: error: moving a temporary object prevents copy elision [-Werror,-Wpessimizing-move]
                               ? new RocksOplogKeyTracker(std::move(rocksGetNextPrefix(_prefix)))
                                                          ^
src/mongo/db/modules/rocks/src/rocks_record_store.cpp:206:59: note: remove std::move call here
                               ? new RocksOplogKeyTracker(std::move(rocksGetNextPrefix(_prefix)))
                                                          ^~~~~~~~~~                           ~
1 error generated.
scons: *** [build/opt/mongo/db/modules/rocks/src/rocks_recovery_unit.o] Error 1
src/mongo/db/modules/rocks/src/rocks_index.cpp:535:38: error: moving a temporary object prevents copy elision [-Werror,-Wpessimizing-move]
            std::string nextPrefix = std::move(rocksGetNextPrefix(_prefix));
                                     ^
src/mongo/db/modules/rocks/src/rocks_index.cpp:535:38: note: remove std::move call here
            std::string nextPrefix = std::move(rocksGetNextPrefix(_prefix));
                                     ^~~~~~~~~~                           ~
1 error generated.
scons: *** [build/opt/mongo/db/modules/rocks/src/rocks_record_store.o] Error 1
1 error generated.
scons: *** [build/opt/mongo/db/modules/rocks/src/rocks_index.o] Error 1
scons: building terminated because of errors.`

**Comment by igorcanadi** [comment]
Hi @mark-lb , thanks for the report. I fixed it in master, can you try again?

BTW if you compile mongo with `--disable-warnings-as-errors`, the warnings will not be treated as errors and the compile should succeed.

**Comment by mark-lb** [comment]
@igorcanadi I tried on r.3.2.8 and it's indeed fixed, thanks!
