### ISSUE TITLE
Q - what's the difference between this and the v3.0-mongorocks branch of mongo in mongodb-partners?

### ISSUE THREAD

**Issue by flozano** [mongodb-partners/mongo-rocks#4]

**Comment by igorcanadi** [comment]
@flozano this repository will serve as a module for MongoDB starting from release 3.2. v3.0-mongorocks branch contains entire mongo repository with integrated rocksdb storage engine for release 3.0. We moved from code-in-mongo-repo model to the model where rocksdb is a spearate module in a separate repository.

**Comment by flozano** [comment]
:+1: thanks for the explanation!
