### ISSUE TITLE
Cherry pick commit 8bb384f (rocksdbCounters should be true by default) to v3.2

### ISSUE THREAD

**Issue by AdallomRoy** [mongodb-partners/mongo-rocks#54]
Can you do it? I know it will hurt performance by 5-10%, but if you set it as default in newer versions, why not merge back?

Thanks.

**Comment by igorcanadi** [comment]
I agree, will do.

**Comment by igorcanadi** [comment]
https://github.com/mongodb-partners/mongo-rocks/commit/a2e502783edef0da8aed3f38275aabbea6fd188f
