### ISSUE TITLE
What happens if a snapshot is released but it is still in use by another thread?

### ISSUE THREAD

**Issue by wolfkdy** [mongodb-partners/mongo-rocks#71]
If mongodb enables readMajority. SnapshotManager will clean unneeded snapshots via a bg thread, see
```
void RocksSnapshotManager::cleanupUnneededSnapshots()
```
```
RocksSnapshotManager::SnapshotHolder::~SnapshotHolder() {  
    if (snapshot != nullptr) {
     db->ReleaseSnapshot(snapshot); 
   }
}
```
code above are executed in mongodb's snapshotThread.
There is a commitedSnapshot in SnapshotManager, which will move forward by time. So the getCommittedSnapshot is variant.

Each time RecoverUnit begins a readTransaction with the option of readMajority, it gets the current commitedSnapshot  from SnapshotManager which may be released by cleanupUnneededSnapshots
```
        options.snapshot = snapshot();
        return _db->Get(options, handle, key, value);
```
```
   const rocksdb::Snapshot* RocksRecoveryUnit::snapshot() {
        if (_readFromMajorityCommittedSnapshot) {
            if (_snapshotHolder.get() == nullptr) {
                _snapshotHolder = _snapshotManager->getCommittedSnapshot();
            }
            return _snapshotHolder->snapshot;
        }
        if (!_snapshot) {
            // RecoveryUnit might be used for writing, so we need to call recordSnapshotId().
            // Order of operations here is important. It needs to be synchronized with
            // _db->Write() and _transaction.commit()
            _transaction.recordSnapshotId();
            _snapshot = _db->GetSnapshot();
        }
        return _snapshot;
    }

```
```
void DBImpl::ReleaseSnapshot(const Snapshot* s) {
  const SnapshotImpl* casted_s = reinterpret_cast<const SnapshotImpl*>(s);
  {
    InstrumentedMutexLock l(&mutex_);
    snapshots_.Delete(casted_s);
  }
  delete casted_s;
} 
```
I strongly doubt that it is a problem which has never been reached because few guys use readMajority

**Comment by wolfkdy** [comment]
releated behavior of WT
https://jira.mongodb.org/browse/WT-3318

**Comment by wolfkdy** [comment]
mongo official guy replied, quoted
```
deyukong, that pattern is permitted. Thread A's transaction makes a copy of the named snapshot, so it is no longer required once begin_transaction has returned.
```
rocks does not have a name-> inner-snapshot mapping. user can operate the real snapshot. 
Currently, I think it should be solved by using a shardptr ot wrap rocks' snapshot.

**Comment by wolfkdy** [comment]
sorry, I was wrong, std::unordered_map<uint64_t, std::shared_ptr<SnapshotHolder>> _snapshotMap is already wrapped by shard_ptr. Each recovery_unit keeps reference by  std::shared_ptr<RocksSnapshotManager::SnapshotHolder> _snapshotHolder;

**Comment by wolfkdy** [comment]
Plz close this issue, thanks！

**Comment by igorcanadi** [comment]
Thanks for verifying our behavior @wolfkdy !
