### ISSUE TITLE
Plz fix typos

### ISSUE THREAD

**Issue by wolfkdy** [mongodb-partners/mongo-rocks#72]
bool cappedMaxDocs() const { invariant(_isCapped); return _cappedMaxDocs; }
bool cappedMaxSize() const { invariant(_isCapped); return _cappedMaxSize; }
the two lines are from master.
It seems the return type is not correct, may be a typo.

**Comment by igorcanadi** [comment]
Hmm, this looks like it was a bad c/p from mongo's code, which still returns bool in the ephemeral storage engine case: https://github.com/mongodb/mongo/blob/master/src/mongo/db/storage/ephemeral_for_test/ephemeral_for_test_record_store.h#L164

However, I'll fix it here.
