### ISSUE TITLE
mongorocks compile failure

### ISSUE THREAD

**Issue by IanWhalen** [mongodb-partners/mongo-rocks#81]
See https://evergreen.mongodb.com/task/mongodb_mongo_master_ubuntu1404_rocksdb_compile_69fd148aafff5bc9c33596b75560f05a6a260f7a_17_06_16_22_17_44/0

The fix is that mongo-rocks should be using the stdx:: polyfills, rather than direcly using boost.

**Comment by igorcanadi** [comment]
Thanks @IanWhalen , should be fixed now.
