### ISSUE TITLE
start mongo with rocksdb error

### ISSUE THREAD

**Issue by cocokeke** [mongodb-partners/mongo-rocks#84]
I make all steps. but last  I start mongod  using the --storageEngine=rocksdb ,it occurs error.
command  ./mongod --dbpath ~/mongo/data --storageEngine=rocksdb

Here is the detail ...

2017-07-03T15:20:57.456+0800 I CONTROL  [initandlisten] MongoDB starting : pid=13857 port=27017 dbpath=/home/zhaoj/mongo/data 64-bit host=zhaoj
2017-07-03T15:20:57.456+0800 I CONTROL  [initandlisten] db version v3.5.9-130-g690302a
2017-07-03T15:20:57.456+0800 I CONTROL  [initandlisten] git version: 690302a49b61d5be3f4dcc285921eb362648055c
2017-07-03T15:20:57.456+0800 I CONTROL  [initandlisten] allocator: tcmalloc
2017-07-03T15:20:57.456+0800 I CONTROL  [initandlisten] modules: none
2017-07-03T15:20:57.456+0800 I CONTROL  [initandlisten] build environment:
2017-07-03T15:20:57.456+0800 I CONTROL  [initandlisten]     distarch: x86_64
2017-07-03T15:20:57.456+0800 I CONTROL  [initandlisten]     target_arch: x86_64
2017-07-03T15:20:57.456+0800 I CONTROL  [initandlisten] options: { storage: { dbPath: "/home/zhaoj/mongo/data", engine: "rocksdb" } }
2017-07-03T15:20:57.456+0800 I STORAGE  [initandlisten] exception in initAndListen: 18656 Cannot start server with an unknown storage engine: rocksdb, terminating
2017-07-03T15:20:57.456+0800 I NETWORK  [initandlisten] shutdown: going to close listening sockets...
2017-07-03T15:20:57.456+0800 I NETWORK  [initandlisten] shutdown: going to flush diaglog...
2017-07-03T15:20:57.456+0800 I CONTROL  [initandlisten] now exiting
2017-07-03T15:20:57.456+0800 I CONTROL  [initandlisten] shutting down with code:100

my mongo version is 3.4 and OS is ubuntu 16.04

**Comment by igorcanadi** [comment]
@cocokeke This error means that you didn't install RocksDB module correctly. What does `ls mongo/src/mongo/db/modules` say?

**Comment by cocokeke** [comment]
ls -la mongo/src/mongo/db/modules

drwxrwxr-x  2 zhaoj zhaoj  4096 7月   3 19:22 .
drwxrwxr-x 24 zhaoj zhaoj 12288 7月   3 19:22 ..
lrwxrwxrwx  1 zhaoj zhaoj    13 7月   3 19:22 rocks -> ./mongo-rocks

**Comment by igorcanadi** [comment]
Ah, I just realized that the instructions in the readme are not correct. Can you try doing:
```
cd mongo/src/mongo/db/modules
ln -sf ../../../../../mongo-rocks rocks
```
And then recompiling Mongo?

**Comment by cocokeke** [comment]
I just did: 
ln -sf /home/zhaoj/jys/mongo-rocksdb-sec/mongo-rocks mongo/src/mongo/db/modules/rocks
but when  I recomplile Mongo, it occurs errors.

/usr/bin/ld.gold: error: /usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/librocksdb.a(delete_scheduler.o): requires unsupported dynamic reloc 11; recompile with -fPIC
/usr/bin/ld.gold: error: /usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/librocksdb.a(delete_scheduler.o): requires dynamic R_X86_64_PC32 reloc against '__cxa_begin_catch' which may overflow at runtime; recompile with -fPIC
/usr/bin/ld.gold: error: /usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/librocksdb.a(delete_scheduler.o): requires dynamic R_X86_64_PC32 reloc against 'memmove' which may overflow at runtime; recompile with -fPIC
/usr/bin/ld.gold: error: /usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/librocksdb.a(delete_scheduler.o): requires dynamic R_X86_64_PC32 reloc against '__cxa_begin_catch' which may overflow at runtime; recompile with -fPIC
/usr/bin/ld.gold: error: /usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/librocksdb.a(delete_scheduler.o): requires dynamic R_X86_64_PC32 reloc against 'memcmp' which may overflow at runtime; recompile with -fPIC
/usr/bin/ld.gold: error: /usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/librocksdb.a(delete_scheduler.o): requires dynamic R_X86_64_PC32 reloc against 'memcmp' which may overflow at runtime; recompile with -fPIC
/usr/bin/ld.gold: error: /usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/librocksdb.a(delete_scheduler.o): requires dynamic R_X86_64_32 reloc which may overflow at runtime; recompile with -fPIC
./util/compression.h:84: error: undefined reference to 'ZSTD_versionNumber'
./util/compression.h:84: error: undefined reference to 'ZSTD_versionNumber'
./util/compression.h:775: error: undefined reference to 'ZSTD_createDCtx'
./util/compression.h:778: error: undefined reference to 'ZSTD_decompress_usingDict'
./util/compression.h:779: error: undefined reference to 'ZSTD_freeDCtx'
./util/compression.h:84: error: undefined reference to 'ZSTD_versionNumber'
./util/compression.h:84: error: undefined reference to 'ZSTD_versionNumber'
./util/compression.h:738: error: undefined reference to 'ZSTD_compressBound'
./util/compression.h:742: error: undefined reference to 'ZSTD_createCCtx'
./util/compression.h:745: error: undefined reference to 'ZSTD_compress_usingDict'
./util/compression.h:746: error: undefined reference to 'ZSTD_freeCCtx'
collect2: error: ld returned 1 exit status
scons: *** [build/opt/mongo/mongod] Error 1
scons: building terminated because of errors.
build/opt/mongo/mongod failed: Error 1

most of the errors containing  "recompile with -fPIC".

**Comment by igorcanadi** [comment]
Can you try compiling rocksdb with -fPIC, like this: `CFLAGS=-fPIC CXXFLAGS=-fPIC make static_library`? Or just try compiling shared library `make shared_library`

**Comment by cocokeke** [comment]
I compiled shared library then recompiled mongo, it finally can start  with option rocksdb.   thank you very much...
