### ISSUE TITLE
merge  SERVER-29655 

### ISSUE THREAD

**Issue by elirevach12** [mongodb-partners/mongo-rocks#85]
Hi ,
We are using your mongo-rocks build (3.2.13) , can you please  merge this fix ?
 https://github.com/mongodb-partners/mongo-rocks/commit/a6ab9e0556bf9423eb671d3a39696402ea5a2990

Thanks

**Comment by ramonfm** [comment]
@igorcanadi , this seems safe to backport to to merge to the v3.2 branch, would you agree?

**Comment by igorcanadi** [comment]
Yup, on it.

**Comment by igorcanadi** [comment]
Wait, it looks like it has been already merged on June 16th: https://github.com/mongodb-partners/mongo-rocks/commits/v3.2. @elirevach12 do you have this latest 3.2 commit in your build?

**Comment by ramonfm** [comment]
@elirevach12 , I don't believe we distribute any binaries with RocksDB compiled in. Looking at the git history I think you need to build with tag r3.2.15

**Comment by elirevach12** [comment]
Thanks .

**Comment by elirevach12** [comment]
Hi Roman
Just to clarify  my point ,   we are using Parcona repo  (and we are very happy with it ) but seems like the this fix is not included in on it r3.2.15 ,and if this is the case , can you please merge it , please .
Or i miss something  .

Thanks

**Comment by ramonfm** [comment]
If you're using a different repo I'm afraid we're not able do much about it -- please contact the owner of that repo to merge the change you need.

Regards,
Ramón.
